bys_turbolinks:
    resource: "@BYSTurbolinksBundle/Resources/config/routing.xml"
    prefix:   /

bys_core:
    resource: "@BYSCoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
