TURBOLINKS_URL=https://raw.githubusercontent.com/turbolinks/turbolinks/v5.0.0/dist/turbolinks.js
TURBOLINKS_SRC=Resources/public/javascript/turbolinks.js

install-dependencies:
	wget $(TURBOLINKS_URL) -O $(TURBOLINKS_SRC)
